apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-posts
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-posts
  template:
    metadata:
      labels:
        app: backend-posts
    spec:
      containers:
      - name: backend-posts
        image: 781942218065.dkr.ecr.us-east-1.amazonaws.com/backend/backend-posts:v1.0.0
        ports:
        - containerPort: 8001
