apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-posts
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-posts
  template:
    metadata:
      labels:
        app: backend-posts
    spec:
      containers:
        - name: backend-posts
          image: 781942218065.dkr.ecr.us-east-1.amazonaws.com/backend/posts:20250502-072838
          ports:
            - containerPort: 8001
          readinessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: posts-index-volume
              mountPath: /usr/app/posts/index.js
              subPath: index.js
      volumes:
        - name: posts-index-volume
          configMap:
            name: backend-posts-index-js

