apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-comments
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-comments
  template:
    metadata:
      labels:
        app: backend-comments
    spec:
      containers:
      - name: backend-comments
        image: 781942218065.dkr.ecr.us-east-1.amazonaws.com/backend/comments:20250503-192949
        ports:
        - containerPort: 8002
