apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-client
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-client
  template:
    metadata:
      labels:
        app: frontend-client
    spec:
      containers:
      - name: frontend-client
        image: 781942218065.dkr.ecr.us-east-1.amazonaws.com/frontend/client:20250502-014735
        ports:
        - containerPort: 3000