apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-query
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-query
  template:
    metadata:
      labels:
        app: backend-query
    spec:
      containers:
        - name: backend-query
          image: 781942218065.dkr.ecr.us-east-1.amazonaws.com/backend/query:20250502-065901
          ports:
            - containerPort: 8003
          readinessProbe:
            tcpSocket:
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: query-index-volume
              mountPath: /usr/app/query/index.js
              subPath: index.js
      volumes:
        - name: query-index-volume
          configMap:
            name: backend-query-index-js

